/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum v1NodeVoteType {
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED',
    TYPE_STAKE_DEPOSITED = 'TYPE_STAKE_DEPOSITED',
    TYPE_STAKE_REMOVED = 'TYPE_STAKE_REMOVED',
    TYPE_FUNDS_DEPOSITED = 'TYPE_FUNDS_DEPOSITED',
    TYPE_SIGNER_ADDED = 'TYPE_SIGNER_ADDED',
    TYPE_SIGNER_REMOVED = 'TYPE_SIGNER_REMOVED',
    TYPE_BRIDGE_STOPPED = 'TYPE_BRIDGE_STOPPED',
    TYPE_BRIDGE_RESUMED = 'TYPE_BRIDGE_RESUMED',
    TYPE_ASSET_LISTED = 'TYPE_ASSET_LISTED',
    TYPE_LIMITS_UPDATED = 'TYPE_LIMITS_UPDATED',
    TYPE_STAKE_TOTAL_SUPPLY = 'TYPE_STAKE_TOTAL_SUPPLY',
    TYPE_SIGNER_THRESHOLD_SET = 'TYPE_SIGNER_THRESHOLD_SET',
    TYPE_GOVERNANCE_VALIDATE_ASSET = 'TYPE_GOVERNANCE_VALIDATE_ASSET',
    TYPE_ETHEREUM_CONTRACT_CALL_RESULT = 'TYPE_ETHEREUM_CONTRACT_CALL_RESULT',
}
