/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { v1NodeSignatureKind } from './v1NodeSignatureKind';

export type v1NodeSignature = {
    /**
     * ID of the resource being signed.
     */
    id?: string;
    /**
     * Kind of resource being signed.
     */
    kind?: v1NodeSignatureKind;
    /**
     * The signature generated by the signer.
     */
    sig?: string;
};

