/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { v2Checkpoint } from './v2Checkpoint';

/**
 * Checkpoint data with the corresponding cursor.
 */
export type v2CheckpointEdge = {
    /**
     * Cursor that can be used to fetch further pages.
     */
    cursor?: string;
    /**
     * Data relating to a single checkpoint generated by the Vega network.
     */
    node?: v2Checkpoint;
};

