/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { vegaMarketData } from './vegaMarketData';

/**
 * Market data with the corresponding cursor.
 */
export type v2MarketDataEdge = {
    /**
     * Cursor that can be used to fetch further pages.
     */
    cursor?: string;
    /**
     * Data generated by a market when open.
     */
    node?: vegaMarketData;
};

