/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum v2Table {
    TABLE_UNSPECIFIED = 'TABLE_UNSPECIFIED',
    TABLE_BALANCES = 'TABLE_BALANCES',
    TABLE_CHECKPOINTS = 'TABLE_CHECKPOINTS',
    TABLE_DELEGATIONS = 'TABLE_DELEGATIONS',
    TABLE_LEDGER = 'TABLE_LEDGER',
    TABLE_ORDERS = 'TABLE_ORDERS',
    TABLE_TRADES = 'TABLE_TRADES',
    TABLE_MARKET_DATA = 'TABLE_MARKET_DATA',
    TABLE_MARGIN_LEVELS = 'TABLE_MARGIN_LEVELS',
    TABLE_POSITIONS = 'TABLE_POSITIONS',
    TABLE_LIQUIDITY_PROVISIONS = 'TABLE_LIQUIDITY_PROVISIONS',
    TABLE_MARKETS = 'TABLE_MARKETS',
    TABLE_DEPOSITS = 'TABLE_DEPOSITS',
    TABLE_WITHDRAWALS = 'TABLE_WITHDRAWALS',
    TABLE_BLOCKS = 'TABLE_BLOCKS',
    TABLE_REWARDS = 'TABLE_REWARDS',
}
