/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { apiHttpBody } from './models/apiHttpBody';
export type { apiv2Candle } from './models/apiv2Candle';
export type { apiv2FundingPayment } from './models/apiv2FundingPayment';
export type { apiv2LiquidityProvision } from './models/apiv2LiquidityProvision';
export type { apiv2ReferralProgram } from './models/apiv2ReferralProgram';
export type { apiv2Team } from './models/apiv2Team';
export type { apiv2VolumeDiscountProgram } from './models/apiv2VolumeDiscountProgram';
export type { commandsv1CancelTransfer } from './models/commandsv1CancelTransfer';
export { ConditionOperator } from './models/ConditionOperator';
export type { eventsv1FundingPayment } from './models/eventsv1FundingPayment';
export { FundingPeriodDataPointSource } from './models/FundingPeriodDataPointSource';
export type { googlerpcStatus } from './models/googlerpcStatus';
export { ListTransfersRequestScope } from './models/ListTransfersRequestScope';
export { MarketTradingMode } from './models/MarketTradingMode';
export { OracleDataSubmissionOracleSource } from './models/OracleDataSubmissionOracleSource';
export { OrderTimeInForce } from './models/OrderTimeInForce';
export type { protobufAny } from './models/protobufAny';
export { protobufNullValue } from './models/protobufNullValue';
export { StopOrderExpiryStrategy } from './models/StopOrderExpiryStrategy';
export { StopOrderRejectionReason } from './models/StopOrderRejectionReason';
export { StopOrderSizeOverrideSetting } from './models/StopOrderSizeOverrideSetting';
export type { StopOrderSizeOverrideValue } from './models/StopOrderSizeOverrideValue';
export { StopOrderTriggerDirection } from './models/StopOrderTriggerDirection';
export type { TransactionResultFailureDetails } from './models/TransactionResultFailureDetails';
export type { TransactionResultSuccessDetails } from './models/TransactionResultSuccessDetails';
export { UpdateMarginModeMode } from './models/UpdateMarginModeMode';
export type { v1AnnounceNode } from './models/v1AnnounceNode';
export type { v1ApplyReferralCode } from './models/v1ApplyReferralCode';
export type { v1AuctionEvent } from './models/v1AuctionEvent';
export type { v1BatchMarketInstructions } from './models/v1BatchMarketInstructions';
export type { v1BatchProposalSubmission } from './models/v1BatchProposalSubmission';
export type { v1BatchProposalSubmissionTerms } from './models/v1BatchProposalSubmissionTerms';
export type { v1BeginBlock } from './models/v1BeginBlock';
export type { v1BusEvent } from './models/v1BusEvent';
export { v1BusEventType } from './models/v1BusEventType';
export type { v1CancelledOrders } from './models/v1CancelledOrders';
export type { v1CheckpointEvent } from './models/v1CheckpointEvent';
export type { v1Condition } from './models/v1Condition';
export type { v1CoreSnapshotData } from './models/v1CoreSnapshotData';
export type { v1CreateReferralSet } from './models/v1CreateReferralSet';
export type { v1CreateReferralSetTeam } from './models/v1CreateReferralSetTeam';
export type { v1Data } from './models/v1Data';
export type { v1DelegateSubmission } from './models/v1DelegateSubmission';
export type { v1DelegationBalanceEvent } from './models/v1DelegationBalanceEvent';
export type { v1DistressedOrders } from './models/v1DistressedOrders';
export type { v1DistressedPositions } from './models/v1DistressedPositions';
export type { v1EndBlock } from './models/v1EndBlock';
export type { v1EpochEvent } from './models/v1EpochEvent';
export type { v1ERC20MultiSigSignerAdded } from './models/v1ERC20MultiSigSignerAdded';
export type { v1ERC20MultiSigSignerEvent } from './models/v1ERC20MultiSigSignerEvent';
export { v1ERC20MultiSigSignerEventType } from './models/v1ERC20MultiSigSignerEventType';
export type { v1ERC20MultiSigSignerRemoved } from './models/v1ERC20MultiSigSignerRemoved';
export type { v1ERC20MultiSigSignerRemovedSubmitter } from './models/v1ERC20MultiSigSignerRemovedSubmitter';
export type { v1ERC20MultiSigThresholdSetEvent } from './models/v1ERC20MultiSigThresholdSetEvent';
export type { v1ETHAddress } from './models/v1ETHAddress';
export type { v1EthereumKeyRotateSubmission } from './models/v1EthereumKeyRotateSubmission';
export type { v1EthereumKeyRotation } from './models/v1EthereumKeyRotation';
export type { v1ExpiredOrders } from './models/v1ExpiredOrders';
export type { v1ExternalData } from './models/v1ExternalData';
export type { v1FeesStats } from './models/v1FeesStats';
export type { v1Filter } from './models/v1Filter';
export type { v1FundingPayments } from './models/v1FundingPayments';
export type { v1FundingPeriod } from './models/v1FundingPeriod';
export type { v1FundingPeriodDataPoint } from './models/v1FundingPeriodDataPoint';
export type { v1IcebergOpts } from './models/v1IcebergOpts';
export type { v1InternalTimeTrigger } from './models/v1InternalTimeTrigger';
export type { v1IssueSignatures } from './models/v1IssueSignatures';
export type { v1JoinTeam } from './models/v1JoinTeam';
export type { v1KeyRotateSubmission } from './models/v1KeyRotateSubmission';
export type { v1KeyRotation } from './models/v1KeyRotation';
export type { v1LedgerMovements } from './models/v1LedgerMovements';
export type { v1LiquidityProvisionAmendment } from './models/v1LiquidityProvisionAmendment';
export type { v1LiquidityProvisionCancellation } from './models/v1LiquidityProvisionCancellation';
export type { v1LiquidityProvisionSubmission } from './models/v1LiquidityProvisionSubmission';
export type { v1LossSocialization } from './models/v1LossSocialization';
export type { v1MakerFeesGenerated } from './models/v1MakerFeesGenerated';
export type { v1MarketEvent } from './models/v1MarketEvent';
export type { v1MarketTick } from './models/v1MarketTick';
export type { v1NodeSignature } from './models/v1NodeSignature';
export { v1NodeSignatureKind } from './models/v1NodeSignatureKind';
export type { v1OneOffGovernanceTransfer } from './models/v1OneOffGovernanceTransfer';
export type { v1OracleDataSubmission } from './models/v1OracleDataSubmission';
export type { v1OrderAmendment } from './models/v1OrderAmendment';
export type { v1OrderCancellation } from './models/v1OrderCancellation';
export type { v1OrderSubmission } from './models/v1OrderSubmission';
export type { v1PaidLiquidityFeesStats } from './models/v1PaidLiquidityFeesStats';
export type { v1PartyActivityStreak } from './models/v1PartyActivityStreak';
export type { v1PartyAmount } from './models/v1PartyAmount';
export type { v1PartyLockedBalance } from './models/v1PartyLockedBalance';
export type { v1PartyMarginModeUpdated } from './models/v1PartyMarginModeUpdated';
export type { v1PartyProfileUpdated } from './models/v1PartyProfileUpdated';
export type { v1PartyVestingBalance } from './models/v1PartyVestingBalance';
export type { v1PartyVestingStats } from './models/v1PartyVestingStats';
export type { v1PartyVestingSummary } from './models/v1PartyVestingSummary';
export type { v1PartyVolumeDiscountStats } from './models/v1PartyVolumeDiscountStats';
export type { v1PositionResolution } from './models/v1PositionResolution';
export type { v1PositionStateEvent } from './models/v1PositionStateEvent';
export type { v1Property } from './models/v1Property';
export type { v1PropertyKey } from './models/v1PropertyKey';
export { v1PropertyKeyType } from './models/v1PropertyKeyType';
export type { v1ProposalSubmission } from './models/v1ProposalSubmission';
export type { v1ProtocolUpgradeDataNodeReady } from './models/v1ProtocolUpgradeDataNodeReady';
export type { v1ProtocolUpgradeEvent } from './models/v1ProtocolUpgradeEvent';
export type { v1ProtocolUpgradeProposal } from './models/v1ProtocolUpgradeProposal';
export { v1ProtocolUpgradeProposalStatus } from './models/v1ProtocolUpgradeProposalStatus';
export type { v1ProtocolUpgradeStarted } from './models/v1ProtocolUpgradeStarted';
export type { v1PubKey } from './models/v1PubKey';
export type { v1RecurringGovernanceTransfer } from './models/v1RecurringGovernanceTransfer';
export type { v1RefereeJoinedReferralSet } from './models/v1RefereeJoinedReferralSet';
export type { v1RefereeJoinedTeam } from './models/v1RefereeJoinedTeam';
export type { v1RefereeStats } from './models/v1RefereeStats';
export type { v1RefereeSwitchedTeam } from './models/v1RefereeSwitchedTeam';
export type { v1ReferralProgramEnded } from './models/v1ReferralProgramEnded';
export type { v1ReferralProgramStarted } from './models/v1ReferralProgramStarted';
export type { v1ReferralProgramUpdated } from './models/v1ReferralProgramUpdated';
export type { v1ReferralSetCreated } from './models/v1ReferralSetCreated';
export type { v1ReferralSetStatsUpdated } from './models/v1ReferralSetStatsUpdated';
export type { v1ReferrerRewardsGenerated } from './models/v1ReferrerRewardsGenerated';
export type { v1RewardPayoutEvent } from './models/v1RewardPayoutEvent';
export type { v1SettleDistressed } from './models/v1SettleDistressed';
export type { v1SettleMarket } from './models/v1SettleMarket';
export type { v1SettlePosition } from './models/v1SettlePosition';
export type { v1Signature } from './models/v1Signature';
export type { v1Signer } from './models/v1Signer';
export type { v1StakeLinking } from './models/v1StakeLinking';
export { v1StakeLinkingStatus } from './models/v1StakeLinkingStatus';
export { v1StakeLinkingType } from './models/v1StakeLinkingType';
export type { v1StateVar } from './models/v1StateVar';
export type { v1StopOrderEvent } from './models/v1StopOrderEvent';
export type { v1StopOrdersCancellation } from './models/v1StopOrdersCancellation';
export type { v1StopOrderSetup } from './models/v1StopOrderSetup';
export type { v1StopOrdersSubmission } from './models/v1StopOrdersSubmission';
export type { v1TeamCreated } from './models/v1TeamCreated';
export type { v1TeamMemberStats } from './models/v1TeamMemberStats';
export type { v1TeamsStatsUpdated } from './models/v1TeamsStatsUpdated';
export type { v1TeamStats } from './models/v1TeamStats';
export type { v1TeamUpdated } from './models/v1TeamUpdated';
export type { v1TimeUpdate } from './models/v1TimeUpdate';
export type { v1TimeWeightedNotionalPositionUpdated } from './models/v1TimeWeightedNotionalPositionUpdated';
export type { v1TradeSettlement } from './models/v1TradeSettlement';
export type { v1TransactionResult } from './models/v1TransactionResult';
export type { v1TransferFees } from './models/v1TransferFees';
export type { v1TransferFeesDiscount } from './models/v1TransferFeesDiscount';
export { v1TransferStatus } from './models/v1TransferStatus';
export type { v1TxErrorEvent } from './models/v1TxErrorEvent';
export type { v1UndelegateSubmission } from './models/v1UndelegateSubmission';
export { v1UndelegateSubmissionMethod } from './models/v1UndelegateSubmissionMethod';
export type { v1UpdateMarginMode } from './models/v1UpdateMarginMode';
export type { v1UpdatePartyProfile } from './models/v1UpdatePartyProfile';
export type { v1UpdateReferralSet } from './models/v1UpdateReferralSet';
export type { v1UpdateReferralSetTeam } from './models/v1UpdateReferralSetTeam';
export type { v1ValidatorRankingEvent } from './models/v1ValidatorRankingEvent';
export type { v1ValidatorScoreEvent } from './models/v1ValidatorScoreEvent';
export type { v1ValidatorUpdate } from './models/v1ValidatorUpdate';
export type { v1VestingBalancesSummary } from './models/v1VestingBalancesSummary';
export type { v1VestingStatsUpdated } from './models/v1VestingStatsUpdated';
export type { v1VolumeDiscountProgramEnded } from './models/v1VolumeDiscountProgramEnded';
export type { v1VolumeDiscountProgramStarted } from './models/v1VolumeDiscountProgramStarted';
export type { v1VolumeDiscountProgramUpdated } from './models/v1VolumeDiscountProgramUpdated';
export type { v1VolumeDiscountStatsUpdated } from './models/v1VolumeDiscountStatsUpdated';
export type { v1VoteSubmission } from './models/v1VoteSubmission';
export type { v1WithdrawSubmission } from './models/v1WithdrawSubmission';
export type { v2AccountBalance } from './models/v2AccountBalance';
export type { v2AccountEdge } from './models/v2AccountEdge';
export type { v2AccountFilter } from './models/v2AccountFilter';
export type { v2AccountsConnection } from './models/v2AccountsConnection';
export type { v2AccountSnapshotPage } from './models/v2AccountSnapshotPage';
export type { v2AccountUpdates } from './models/v2AccountUpdates';
export type { v2AggregatedBalance } from './models/v2AggregatedBalance';
export type { v2AggregatedBalanceConnection } from './models/v2AggregatedBalanceConnection';
export type { v2AggregatedBalanceEdge } from './models/v2AggregatedBalanceEdge';
export type { v2AggregatedLedgerEntriesConnection } from './models/v2AggregatedLedgerEntriesConnection';
export type { v2AggregatedLedgerEntriesEdge } from './models/v2AggregatedLedgerEntriesEdge';
export type { v2AggregatedLedgerEntry } from './models/v2AggregatedLedgerEntry';
export type { v2AssetEdge } from './models/v2AssetEdge';
export type { v2AssetsConnection } from './models/v2AssetsConnection';
export type { v2CandleDataConnection } from './models/v2CandleDataConnection';
export type { v2CandleEdge } from './models/v2CandleEdge';
export type { v2Checkpoint } from './models/v2Checkpoint';
export type { v2CheckpointEdge } from './models/v2CheckpointEdge';
export type { v2CheckpointsConnection } from './models/v2CheckpointsConnection';
export type { v2CollateralIncreaseEstimate } from './models/v2CollateralIncreaseEstimate';
export type { v2CoreSnapshotConnection } from './models/v2CoreSnapshotConnection';
export type { v2CoreSnapshotEdge } from './models/v2CoreSnapshotEdge';
export type { v2DateRange } from './models/v2DateRange';
export type { v2DelegationEdge } from './models/v2DelegationEdge';
export type { v2DelegationsConnection } from './models/v2DelegationsConnection';
export type { v2DepositEdge } from './models/v2DepositEdge';
export type { v2DepositsConnection } from './models/v2DepositsConnection';
export type { v2EpochRewardSummaryConnection } from './models/v2EpochRewardSummaryConnection';
export type { v2EpochRewardSummaryEdge } from './models/v2EpochRewardSummaryEdge';
export type { v2ERC20MultiSigSignerAddedBundle } from './models/v2ERC20MultiSigSignerAddedBundle';
export type { v2ERC20MultiSigSignerAddedBundleEdge } from './models/v2ERC20MultiSigSignerAddedBundleEdge';
export type { v2ERC20MultiSigSignerAddedConnection } from './models/v2ERC20MultiSigSignerAddedConnection';
export type { v2ERC20MultiSigSignerRemovedBundle } from './models/v2ERC20MultiSigSignerRemovedBundle';
export type { v2ERC20MultiSigSignerRemovedBundleEdge } from './models/v2ERC20MultiSigSignerRemovedBundleEdge';
export type { v2ERC20MultiSigSignerRemovedConnection } from './models/v2ERC20MultiSigSignerRemovedConnection';
export type { v2EstimateFeeResponse } from './models/v2EstimateFeeResponse';
export type { v2EstimateMarginResponse } from './models/v2EstimateMarginResponse';
export type { v2EstimatePositionResponse } from './models/v2EstimatePositionResponse';
export type { v2EstimateTransferFeeResponse } from './models/v2EstimateTransferFeeResponse';
export type { v2EthereumKeyRotationEdge } from './models/v2EthereumKeyRotationEdge';
export type { v2EthereumKeyRotationsConnection } from './models/v2EthereumKeyRotationsConnection';
export type { v2FeesStatsForParty } from './models/v2FeesStatsForParty';
export type { v2FundingPaymentConnection } from './models/v2FundingPaymentConnection';
export type { v2FundingPaymentEdge } from './models/v2FundingPaymentEdge';
export type { v2FundingPeriodConnection } from './models/v2FundingPeriodConnection';
export type { v2FundingPeriodDataPointConnection } from './models/v2FundingPeriodDataPointConnection';
export type { v2FundingPeriodDataPointEdge } from './models/v2FundingPeriodDataPointEdge';
export type { v2FundingPeriodEdge } from './models/v2FundingPeriodEdge';
export type { v2Game } from './models/v2Game';
export type { v2GameEdge } from './models/v2GameEdge';
export type { v2GamesConnection } from './models/v2GamesConnection';
export type { v2GetActiveNetworkHistoryPeerAddressesResponse } from './models/v2GetActiveNetworkHistoryPeerAddressesResponse';
export type { v2GetAssetResponse } from './models/v2GetAssetResponse';
export type { v2GetCurrentReferralProgramResponse } from './models/v2GetCurrentReferralProgramResponse';
export type { v2GetCurrentVolumeDiscountProgramResponse } from './models/v2GetCurrentVolumeDiscountProgramResponse';
export type { v2GetDepositResponse } from './models/v2GetDepositResponse';
export type { v2GetEpochResponse } from './models/v2GetEpochResponse';
export type { v2GetERC20ListAssetBundleResponse } from './models/v2GetERC20ListAssetBundleResponse';
export type { v2GetERC20SetAssetLimitsBundleResponse } from './models/v2GetERC20SetAssetLimitsBundleResponse';
export type { v2GetERC20WithdrawalApprovalResponse } from './models/v2GetERC20WithdrawalApprovalResponse';
export type { v2GetFeesStatsForPartyResponse } from './models/v2GetFeesStatsForPartyResponse';
export type { v2GetFeesStatsResponse } from './models/v2GetFeesStatsResponse';
export type { v2GetGovernanceDataResponse } from './models/v2GetGovernanceDataResponse';
export type { v2GetLastTradeResponse } from './models/v2GetLastTradeResponse';
export type { v2GetLatestMarketDataResponse } from './models/v2GetLatestMarketDataResponse';
export type { v2GetLatestMarketDepthResponse } from './models/v2GetLatestMarketDepthResponse';
export type { v2GetMarketDataHistoryByIDResponse } from './models/v2GetMarketDataHistoryByIDResponse';
export type { v2GetMarketResponse } from './models/v2GetMarketResponse';
export type { v2GetMostRecentNetworkHistorySegmentResponse } from './models/v2GetMostRecentNetworkHistorySegmentResponse';
export type { v2GetNetworkDataResponse } from './models/v2GetNetworkDataResponse';
export type { v2GetNetworkHistoryBootstrapPeersResponse } from './models/v2GetNetworkHistoryBootstrapPeersResponse';
export type { v2GetNetworkHistoryStatusResponse } from './models/v2GetNetworkHistoryStatusResponse';
export type { v2GetNetworkLimitsResponse } from './models/v2GetNetworkLimitsResponse';
export type { v2GetNetworkParameterResponse } from './models/v2GetNetworkParameterResponse';
export type { v2GetNodeResponse } from './models/v2GetNodeResponse';
export type { v2GetOracleSpecResponse } from './models/v2GetOracleSpecResponse';
export type { v2GetOrderResponse } from './models/v2GetOrderResponse';
export type { v2GetPartyActivityStreakResponse } from './models/v2GetPartyActivityStreakResponse';
export type { v2GetPartyResponse } from './models/v2GetPartyResponse';
export type { v2GetPartyVestingStatsResponse } from './models/v2GetPartyVestingStatsResponse';
export type { v2GetProtocolUpgradeStatusResponse } from './models/v2GetProtocolUpgradeStatusResponse';
export type { v2GetReferralSetStatsResponse } from './models/v2GetReferralSetStatsResponse';
export type { v2GetRiskFactorsResponse } from './models/v2GetRiskFactorsResponse';
export type { v2GetStakeResponse } from './models/v2GetStakeResponse';
export type { v2GetStopOrderResponse } from './models/v2GetStopOrderResponse';
export type { v2GetTimeWeightedNotionalPositionResponse } from './models/v2GetTimeWeightedNotionalPositionResponse';
export type { v2GetTotalTransferFeeDiscountResponse } from './models/v2GetTotalTransferFeeDiscountResponse';
export type { v2GetTransferResponse } from './models/v2GetTransferResponse';
export type { v2GetVegaTimeResponse } from './models/v2GetVegaTimeResponse';
export type { v2GetVestingBalancesSummaryResponse } from './models/v2GetVestingBalancesSummaryResponse';
export type { v2GetVolumeDiscountStatsResponse } from './models/v2GetVolumeDiscountStatsResponse';
export type { v2GetWithdrawalResponse } from './models/v2GetWithdrawalResponse';
export type { v2GovernanceDataConnection } from './models/v2GovernanceDataConnection';
export type { v2GovernanceDataEdge } from './models/v2GovernanceDataEdge';
export type { v2HistorySegment } from './models/v2HistorySegment';
export type { v2IndividualGameEntities } from './models/v2IndividualGameEntities';
export type { v2IndividualGameEntity } from './models/v2IndividualGameEntity';
export type { v2InfoResponse } from './models/v2InfoResponse';
export type { v2IntervalToCandleId } from './models/v2IntervalToCandleId';
export type { v2KeyRotationConnection } from './models/v2KeyRotationConnection';
export type { v2KeyRotationEdge } from './models/v2KeyRotationEdge';
export type { v2LedgerEntryFilter } from './models/v2LedgerEntryFilter';
export type { v2LiquidationEstimate } from './models/v2LiquidationEstimate';
export type { v2LiquidationPrice } from './models/v2LiquidationPrice';
export type { v2LiquidityProvider } from './models/v2LiquidityProvider';
export type { v2LiquidityProviderConnection } from './models/v2LiquidityProviderConnection';
export type { v2LiquidityProviderEdge } from './models/v2LiquidityProviderEdge';
export type { v2LiquidityProvisionsConnection } from './models/v2LiquidityProvisionsConnection';
export type { v2LiquidityProvisionsEdge } from './models/v2LiquidityProvisionsEdge';
export type { v2LiquidityProvisionsWithPendingConnection } from './models/v2LiquidityProvisionsWithPendingConnection';
export type { v2LiquidityProvisionWithPendingEdge } from './models/v2LiquidityProvisionWithPendingEdge';
export type { v2ListAccountsResponse } from './models/v2ListAccountsResponse';
export type { v2ListAllLiquidityProvisionsResponse } from './models/v2ListAllLiquidityProvisionsResponse';
export type { v2ListAllNetworkHistorySegmentsResponse } from './models/v2ListAllNetworkHistorySegmentsResponse';
export type { v2ListAllPositionsResponse } from './models/v2ListAllPositionsResponse';
export type { v2ListAssetsResponse } from './models/v2ListAssetsResponse';
export type { v2ListBalanceChangesResponse } from './models/v2ListBalanceChangesResponse';
export type { v2ListCandleDataResponse } from './models/v2ListCandleDataResponse';
export type { v2ListCandleIntervalsResponse } from './models/v2ListCandleIntervalsResponse';
export type { v2ListCheckpointsResponse } from './models/v2ListCheckpointsResponse';
export type { v2ListCoreSnapshotsResponse } from './models/v2ListCoreSnapshotsResponse';
export type { v2ListDelegationsResponse } from './models/v2ListDelegationsResponse';
export type { v2ListDepositsResponse } from './models/v2ListDepositsResponse';
export type { v2ListEntitiesResponse } from './models/v2ListEntitiesResponse';
export type { v2ListEpochRewardSummariesResponse } from './models/v2ListEpochRewardSummariesResponse';
export type { v2ListERC20MultiSigSignerAddedBundlesResponse } from './models/v2ListERC20MultiSigSignerAddedBundlesResponse';
export type { v2ListERC20MultiSigSignerRemovedBundlesResponse } from './models/v2ListERC20MultiSigSignerRemovedBundlesResponse';
export type { v2ListEthereumKeyRotationsResponse } from './models/v2ListEthereumKeyRotationsResponse';
export type { v2ListFundingPaymentsResponse } from './models/v2ListFundingPaymentsResponse';
export type { v2ListFundingPeriodDataPointsResponse } from './models/v2ListFundingPeriodDataPointsResponse';
export type { v2ListFundingPeriodsResponse } from './models/v2ListFundingPeriodsResponse';
export type { v2ListGamesResponse } from './models/v2ListGamesResponse';
export { v2ListGovernanceDataRequestType } from './models/v2ListGovernanceDataRequestType';
export type { v2ListGovernanceDataResponse } from './models/v2ListGovernanceDataResponse';
export type { v2ListKeyRotationsResponse } from './models/v2ListKeyRotationsResponse';
export type { v2ListLatestMarketDataResponse } from './models/v2ListLatestMarketDataResponse';
export type { v2ListLedgerEntriesResponse } from './models/v2ListLedgerEntriesResponse';
export type { v2ListLiquidityProvidersResponse } from './models/v2ListLiquidityProvidersResponse';
export type { v2ListLiquidityProvisionsResponse } from './models/v2ListLiquidityProvisionsResponse';
export type { v2ListMarginLevelsResponse } from './models/v2ListMarginLevelsResponse';
export type { v2ListMarketsResponse } from './models/v2ListMarketsResponse';
export type { v2ListNetworkParametersResponse } from './models/v2ListNetworkParametersResponse';
export type { v2ListNodeSignaturesResponse } from './models/v2ListNodeSignaturesResponse';
export type { v2ListNodesResponse } from './models/v2ListNodesResponse';
export type { v2ListOracleDataResponse } from './models/v2ListOracleDataResponse';
export type { v2ListOracleSpecsResponse } from './models/v2ListOracleSpecsResponse';
export type { v2ListOrdersResponse } from './models/v2ListOrdersResponse';
export type { v2ListOrderVersionsResponse } from './models/v2ListOrderVersionsResponse';
export type { v2ListPaidLiquidityFeesResponse } from './models/v2ListPaidLiquidityFeesResponse';
export type { v2ListPartiesProfilesResponse } from './models/v2ListPartiesProfilesResponse';
export type { v2ListPartiesResponse } from './models/v2ListPartiesResponse';
export type { v2ListPartyMarginModesResponse } from './models/v2ListPartyMarginModesResponse';
export type { v2ListPositionsResponse } from './models/v2ListPositionsResponse';
export type { v2ListProtocolUpgradeProposalsResponse } from './models/v2ListProtocolUpgradeProposalsResponse';
export type { v2ListReferralSetRefereesResponse } from './models/v2ListReferralSetRefereesResponse';
export type { v2ListReferralSetsResponse } from './models/v2ListReferralSetsResponse';
export type { v2ListRewardsResponse } from './models/v2ListRewardsResponse';
export type { v2ListRewardSummariesResponse } from './models/v2ListRewardSummariesResponse';
export type { v2ListStopOrdersResponse } from './models/v2ListStopOrdersResponse';
export type { v2ListSuccessorMarketsResponse } from './models/v2ListSuccessorMarketsResponse';
export type { v2ListTeamMembersStatisticsResponse } from './models/v2ListTeamMembersStatisticsResponse';
export type { v2ListTeamRefereeHistoryResponse } from './models/v2ListTeamRefereeHistoryResponse';
export type { v2ListTeamRefereesResponse } from './models/v2ListTeamRefereesResponse';
export type { v2ListTeamsResponse } from './models/v2ListTeamsResponse';
export type { v2ListTeamsStatisticsResponse } from './models/v2ListTeamsStatisticsResponse';
export type { v2ListTradesResponse } from './models/v2ListTradesResponse';
export type { v2ListTransfersResponse } from './models/v2ListTransfersResponse';
export type { v2ListVotesResponse } from './models/v2ListVotesResponse';
export type { v2ListWithdrawalsResponse } from './models/v2ListWithdrawalsResponse';
export type { v2MarginConnection } from './models/v2MarginConnection';
export type { v2MarginEdge } from './models/v2MarginEdge';
export type { v2MarginEstimate } from './models/v2MarginEstimate';
export type { v2MarketConnection } from './models/v2MarketConnection';
export type { v2MarketDataConnection } from './models/v2MarketDataConnection';
export type { v2MarketDataEdge } from './models/v2MarketDataEdge';
export type { v2MarketEdge } from './models/v2MarketEdge';
export type { v2NetworkParameterConnection } from './models/v2NetworkParameterConnection';
export type { v2NetworkParameterEdge } from './models/v2NetworkParameterEdge';
export type { v2NodeBasic } from './models/v2NodeBasic';
export type { v2NodeEdge } from './models/v2NodeEdge';
export type { v2NodesConnection } from './models/v2NodesConnection';
export type { v2NodeSignatureEdge } from './models/v2NodeSignatureEdge';
export type { v2NodeSignaturesConnection } from './models/v2NodeSignaturesConnection';
export type { v2ObserveAccountsResponse } from './models/v2ObserveAccountsResponse';
export type { v2ObserveCandleDataResponse } from './models/v2ObserveCandleDataResponse';
export type { v2ObserveEventBusResponse } from './models/v2ObserveEventBusResponse';
export type { v2ObserveGovernanceResponse } from './models/v2ObserveGovernanceResponse';
export type { v2ObserveLedgerMovementsResponse } from './models/v2ObserveLedgerMovementsResponse';
export type { v2ObserveLiquidityProvisionsResponse } from './models/v2ObserveLiquidityProvisionsResponse';
export type { v2ObserveMarginLevelsResponse } from './models/v2ObserveMarginLevelsResponse';
export type { v2ObserveMarketsDataResponse } from './models/v2ObserveMarketsDataResponse';
export type { v2ObserveMarketsDepthResponse } from './models/v2ObserveMarketsDepthResponse';
export type { v2ObserveMarketsDepthUpdatesResponse } from './models/v2ObserveMarketsDepthUpdatesResponse';
export type { v2ObserveOrdersResponse } from './models/v2ObserveOrdersResponse';
export type { v2ObservePositionsResponse } from './models/v2ObservePositionsResponse';
export type { v2ObserveTradesResponse } from './models/v2ObserveTradesResponse';
export type { v2ObserveTransactionResultsResponse } from './models/v2ObserveTransactionResultsResponse';
export type { v2ObserveVotesResponse } from './models/v2ObserveVotesResponse';
export type { v2OracleDataConnection } from './models/v2OracleDataConnection';
export type { v2OracleDataEdge } from './models/v2OracleDataEdge';
export type { v2OracleSpecEdge } from './models/v2OracleSpecEdge';
export type { v2OracleSpecsConnection } from './models/v2OracleSpecsConnection';
export type { v2OrderConnection } from './models/v2OrderConnection';
export type { v2OrderEdge } from './models/v2OrderEdge';
export type { v2OrderFilter } from './models/v2OrderFilter';
export type { v2OrderInfo } from './models/v2OrderInfo';
export type { v2OrderSnapshotPage } from './models/v2OrderSnapshotPage';
export type { v2OrderUpdates } from './models/v2OrderUpdates';
export type { v2PageInfo } from './models/v2PageInfo';
export type { v2Pagination } from './models/v2Pagination';
export type { v2PaidLiquidityFeesConnection } from './models/v2PaidLiquidityFeesConnection';
export type { v2PaidLiquidityFeesEdge } from './models/v2PaidLiquidityFeesEdge';
export type { v2PartiesProfilesConnection } from './models/v2PartiesProfilesConnection';
export type { v2PartyConnection } from './models/v2PartyConnection';
export type { v2PartyEdge } from './models/v2PartyEdge';
export type { v2PartyMarginMode } from './models/v2PartyMarginMode';
export type { v2PartyMarginModeEdge } from './models/v2PartyMarginModeEdge';
export type { v2PartyMarginModesConnection } from './models/v2PartyMarginModesConnection';
export type { v2PartyProfileEdge } from './models/v2PartyProfileEdge';
export type { v2PingResponse } from './models/v2PingResponse';
export type { v2PositionConnection } from './models/v2PositionConnection';
export type { v2PositionEdge } from './models/v2PositionEdge';
export type { v2PositionsFilter } from './models/v2PositionsFilter';
export type { v2PositionSnapshotPage } from './models/v2PositionSnapshotPage';
export type { v2PositionUpdates } from './models/v2PositionUpdates';
export type { v2ProtocolUpgradeProposalConnection } from './models/v2ProtocolUpgradeProposalConnection';
export type { v2ProtocolUpgradeProposalEdge } from './models/v2ProtocolUpgradeProposalEdge';
export type { v2QuantumRewardsPerEpoch } from './models/v2QuantumRewardsPerEpoch';
export type { v2QuantumVolumesPerEpoch } from './models/v2QuantumVolumesPerEpoch';
export type { v2ReferralSet } from './models/v2ReferralSet';
export type { v2ReferralSetConnection } from './models/v2ReferralSetConnection';
export type { v2ReferralSetEdge } from './models/v2ReferralSetEdge';
export type { v2ReferralSetReferee } from './models/v2ReferralSetReferee';
export type { v2ReferralSetRefereeConnection } from './models/v2ReferralSetRefereeConnection';
export type { v2ReferralSetRefereeEdge } from './models/v2ReferralSetRefereeEdge';
export type { v2ReferralSetStats } from './models/v2ReferralSetStats';
export type { v2ReferralSetStatsConnection } from './models/v2ReferralSetStatsConnection';
export type { v2ReferralSetStatsEdge } from './models/v2ReferralSetStatsEdge';
export type { v2RewardEdge } from './models/v2RewardEdge';
export type { v2RewardsConnection } from './models/v2RewardsConnection';
export type { v2RewardSummaryFilter } from './models/v2RewardSummaryFilter';
export type { v2StakeLinkingEdge } from './models/v2StakeLinkingEdge';
export type { v2StakesConnection } from './models/v2StakesConnection';
export type { v2StopOrderConnection } from './models/v2StopOrderConnection';
export type { v2StopOrderEdge } from './models/v2StopOrderEdge';
export type { v2StopOrderFilter } from './models/v2StopOrderFilter';
export type { v2SuccessorMarket } from './models/v2SuccessorMarket';
export type { v2SuccessorMarketConnection } from './models/v2SuccessorMarketConnection';
export type { v2SuccessorMarketEdge } from './models/v2SuccessorMarketEdge';
export { v2Table } from './models/v2Table';
export type { v2TeamConnection } from './models/v2TeamConnection';
export type { v2TeamEdge } from './models/v2TeamEdge';
export type { v2TeamGameEntities } from './models/v2TeamGameEntities';
export type { v2TeamGameEntity } from './models/v2TeamGameEntity';
export type { v2TeamGameParticipation } from './models/v2TeamGameParticipation';
export type { v2TeamMembersStatisticsConnection } from './models/v2TeamMembersStatisticsConnection';
export type { v2TeamMemberStatistics } from './models/v2TeamMemberStatistics';
export type { v2TeamMemberStatisticsEdge } from './models/v2TeamMemberStatisticsEdge';
export type { v2TeamReferee } from './models/v2TeamReferee';
export type { v2TeamRefereeConnection } from './models/v2TeamRefereeConnection';
export type { v2TeamRefereeEdge } from './models/v2TeamRefereeEdge';
export type { v2TeamRefereeHistory } from './models/v2TeamRefereeHistory';
export type { v2TeamRefereeHistoryConnection } from './models/v2TeamRefereeHistoryConnection';
export type { v2TeamRefereeHistoryEdge } from './models/v2TeamRefereeHistoryEdge';
export type { v2TeamsStatisticsConnection } from './models/v2TeamsStatisticsConnection';
export type { v2TeamStatistics } from './models/v2TeamStatistics';
export type { v2TeamStatisticsEdge } from './models/v2TeamStatisticsEdge';
export type { v2TimeWeightedNotionalPosition } from './models/v2TimeWeightedNotionalPosition';
export type { v2TradeConnection } from './models/v2TradeConnection';
export type { v2TradeEdge } from './models/v2TradeEdge';
export type { v2TransferConnection } from './models/v2TransferConnection';
export { v2TransferDirection } from './models/v2TransferDirection';
export type { v2TransferEdge } from './models/v2TransferEdge';
export type { v2TransferNode } from './models/v2TransferNode';
export type { v2VolumeDiscountStats } from './models/v2VolumeDiscountStats';
export type { v2VolumeDiscountStatsConnection } from './models/v2VolumeDiscountStatsConnection';
export type { v2VolumeDiscountStatsEdge } from './models/v2VolumeDiscountStatsEdge';
export type { v2VoteConnection } from './models/v2VoteConnection';
export type { v2VoteEdge } from './models/v2VoteEdge';
export type { v2WithdrawalEdge } from './models/v2WithdrawalEdge';
export type { v2WithdrawalsConnection } from './models/v2WithdrawalsConnection';
export type { vegaAccount } from './models/vegaAccount';
export type { vegaAccountDetails } from './models/vegaAccountDetails';
export { vegaAccountType } from './models/vegaAccountType';
export type { vegaAsset } from './models/vegaAsset';
export type { vegaAssetDetails } from './models/vegaAssetDetails';
export type { vegaAssetDetailsUpdate } from './models/vegaAssetDetailsUpdate';
export { vegaAssetStatus } from './models/vegaAssetStatus';
export type { vegaAuctionDuration } from './models/vegaAuctionDuration';
export { vegaAuctionTrigger } from './models/vegaAuctionTrigger';
export type { vegaBatchProposalTerms } from './models/vegaBatchProposalTerms';
export type { vegaBatchProposalTermsChange } from './models/vegaBatchProposalTermsChange';
export type { vegaBenefitTier } from './models/vegaBenefitTier';
export type { vegaBuiltinAsset } from './models/vegaBuiltinAsset';
export type { vegaCancelTransfer } from './models/vegaCancelTransfer';
export type { vegaCancelTransferConfiguration } from './models/vegaCancelTransferConfiguration';
export type { vegacommandsv1OneOffTransfer } from './models/vegacommandsv1OneOffTransfer';
export type { vegacommandsv1RecurringTransfer } from './models/vegacommandsv1RecurringTransfer';
export type { vegacommandsv1Transfer } from './models/vegacommandsv1Transfer';
export type { vegaCompositePriceConfiguration } from './models/vegaCompositePriceConfiguration';
export type { vegaCompositePriceSource } from './models/vegaCompositePriceSource';
export type { vegaCompositePriceState } from './models/vegaCompositePriceState';
export { vegaCompositePriceType } from './models/vegaCompositePriceType';
export type { vegaDataSourceDefinition } from './models/vegaDataSourceDefinition';
export type { vegaDataSourceDefinitionExternal } from './models/vegaDataSourceDefinitionExternal';
export type { vegaDataSourceDefinitionInternal } from './models/vegaDataSourceDefinitionInternal';
export type { vegaDataSourceSpec } from './models/vegaDataSourceSpec';
export type { vegaDataSourceSpecConfiguration } from './models/vegaDataSourceSpecConfiguration';
export type { vegaDataSourceSpecConfigurationTime } from './models/vegaDataSourceSpecConfigurationTime';
export type { vegaDataSourceSpecConfigurationTimeTrigger } from './models/vegaDataSourceSpecConfigurationTimeTrigger';
export { vegaDataSourceSpecStatus } from './models/vegaDataSourceSpecStatus';
export type { vegaDataSourceSpecToFutureBinding } from './models/vegaDataSourceSpecToFutureBinding';
export type { vegaDataSourceSpecToPerpetualBinding } from './models/vegaDataSourceSpecToPerpetualBinding';
export type { vegaDelegation } from './models/vegaDelegation';
export type { vegaDeposit } from './models/vegaDeposit';
export { vegaDepositStatus } from './models/vegaDepositStatus';
export { vegaDispatchMetric } from './models/vegaDispatchMetric';
export type { vegaDispatchStrategy } from './models/vegaDispatchStrategy';
export { vegaDistributionStrategy } from './models/vegaDistributionStrategy';
export { vegaEntityScope } from './models/vegaEntityScope';
export type { vegaEpoch } from './models/vegaEpoch';
export { vegaEpochAction } from './models/vegaEpochAction';
export type { vegaEpochData } from './models/vegaEpochData';
export type { vegaEpochRewardSummary } from './models/vegaEpochRewardSummary';
export type { vegaEpochTimestamps } from './models/vegaEpochTimestamps';
export type { vegaERC20 } from './models/vegaERC20';
export type { vegaERC20Update } from './models/vegaERC20Update';
export type { vegaErc20WithdrawExt } from './models/vegaErc20WithdrawExt';
export type { vegaEthCallSpec } from './models/vegaEthCallSpec';
export type { vegaEthCallTrigger } from './models/vegaEthCallTrigger';
export type { vegaEthTimeTrigger } from './models/vegaEthTimeTrigger';
export type { vegaeventsv1OneOffTransfer } from './models/vegaeventsv1OneOffTransfer';
export type { vegaeventsv1RecurringTransfer } from './models/vegaeventsv1RecurringTransfer';
export type { vegaeventsv1Transfer } from './models/vegaeventsv1Transfer';
export type { vegaExternalDataSourceSpec } from './models/vegaExternalDataSourceSpec';
export type { vegaFee } from './models/vegaFee';
export type { vegaFeeFactors } from './models/vegaFeeFactors';
export type { vegaFees } from './models/vegaFees';
export type { vegaFuture } from './models/vegaFuture';
export type { vegaFutureProduct } from './models/vegaFutureProduct';
export type { vegaGovernanceData } from './models/vegaGovernanceData';
export { vegaGovernanceDataType } from './models/vegaGovernanceDataType';
export { vegaGovernanceTransferType } from './models/vegaGovernanceTransferType';
export type { vegaIcebergOrder } from './models/vegaIcebergOrder';
export { vegaIndividualScope } from './models/vegaIndividualScope';
export type { vegaInstrument } from './models/vegaInstrument';
export type { vegaInstrumentConfiguration } from './models/vegaInstrumentConfiguration';
export type { vegaInstrumentMetadata } from './models/vegaInstrumentMetadata';
export type { vegaLedgerEntry } from './models/vegaLedgerEntry';
export type { vegaLedgerMovement } from './models/vegaLedgerMovement';
export type { vegaLiquidationStrategy } from './models/vegaLiquidationStrategy';
export type { vegaLiquidityFeeSettings } from './models/vegaLiquidityFeeSettings';
export { vegaLiquidityFeeSettingsMethod } from './models/vegaLiquidityFeeSettingsMethod';
export type { vegaLiquidityMonitoringParameters } from './models/vegaLiquidityMonitoringParameters';
export type { vegaLiquidityOrder } from './models/vegaLiquidityOrder';
export type { vegaLiquidityOrderReference } from './models/vegaLiquidityOrderReference';
export type { vegaLiquidityProviderFeeShare } from './models/vegaLiquidityProviderFeeShare';
export type { vegaLiquidityProviderSLA } from './models/vegaLiquidityProviderSLA';
export type { vegaLiquidityProvision } from './models/vegaLiquidityProvision';
export { vegaLiquidityProvisionStatus } from './models/vegaLiquidityProvisionStatus';
export type { vegaLiquiditySLAParameters } from './models/vegaLiquiditySLAParameters';
export type { vegaLogNormalModelParams } from './models/vegaLogNormalModelParams';
export type { vegaLogNormalRiskModel } from './models/vegaLogNormalRiskModel';
export type { vegaMarginCalculator } from './models/vegaMarginCalculator';
export type { vegaMarginLevels } from './models/vegaMarginLevels';
export { vegaMarginMode } from './models/vegaMarginMode';
export type { vegaMarket } from './models/vegaMarket';
export type { vegaMarketData } from './models/vegaMarketData';
export type { vegaMarketDepth } from './models/vegaMarketDepth';
export type { vegaMarketDepthUpdate } from './models/vegaMarketDepthUpdate';
export { vegaMarketState } from './models/vegaMarketState';
export { vegaMarketStateUpdateType } from './models/vegaMarketStateUpdateType';
export type { vegaMarketTimestamps } from './models/vegaMarketTimestamps';
export type { vegaMetadata } from './models/vegaMetadata';
export type { vegaNetworkLimits } from './models/vegaNetworkLimits';
export type { vegaNetworkParameter } from './models/vegaNetworkParameter';
export type { vegaNewAsset } from './models/vegaNewAsset';
export type { vegaNewFreeform } from './models/vegaNewFreeform';
export type { vegaNewMarket } from './models/vegaNewMarket';
export type { vegaNewMarketConfiguration } from './models/vegaNewMarketConfiguration';
export type { vegaNewSpotMarket } from './models/vegaNewSpotMarket';
export type { vegaNewSpotMarketConfiguration } from './models/vegaNewSpotMarketConfiguration';
export type { vegaNewTransfer } from './models/vegaNewTransfer';
export type { vegaNewTransferConfiguration } from './models/vegaNewTransferConfiguration';
export type { vegaNode } from './models/vegaNode';
export type { vegaNodeData } from './models/vegaNodeData';
export type { vegaNodeSet } from './models/vegaNodeSet';
export { vegaNodeStatus } from './models/vegaNodeStatus';
export type { vegaNormaliser } from './models/vegaNormaliser';
export type { vegaOneOffTransfer } from './models/vegaOneOffTransfer';
export type { vegaOracleData } from './models/vegaOracleData';
export type { vegaOracleSpec } from './models/vegaOracleSpec';
export type { vegaOrder } from './models/vegaOrder';
export { vegaOrderError } from './models/vegaOrderError';
export { vegaOrderStatus } from './models/vegaOrderStatus';
export { vegaOrderType } from './models/vegaOrderType';
export type { vegaParty } from './models/vegaParty';
export type { vegaPartyProfile } from './models/vegaPartyProfile';
export type { vegaPeggedOrder } from './models/vegaPeggedOrder';
export { vegaPeggedReference } from './models/vegaPeggedReference';
export type { vegaPerpetual } from './models/vegaPerpetual';
export type { vegaPerpetualData } from './models/vegaPerpetualData';
export type { vegaPerpetualProduct } from './models/vegaPerpetualProduct';
export type { vegaPosition } from './models/vegaPosition';
export { vegaPositionStatus } from './models/vegaPositionStatus';
export type { vegaPostTransferBalance } from './models/vegaPostTransferBalance';
export type { vegaPriceLevel } from './models/vegaPriceLevel';
export type { vegaPriceMonitoringBounds } from './models/vegaPriceMonitoringBounds';
export type { vegaPriceMonitoringParameters } from './models/vegaPriceMonitoringParameters';
export type { vegaPriceMonitoringSettings } from './models/vegaPriceMonitoringSettings';
export type { vegaPriceMonitoringTrigger } from './models/vegaPriceMonitoringTrigger';
export type { vegaProductData } from './models/vegaProductData';
export type { vegaProposal } from './models/vegaProposal';
export { vegaProposalError } from './models/vegaProposalError';
export type { vegaProposalParameters } from './models/vegaProposalParameters';
export type { vegaProposalRationale } from './models/vegaProposalRationale';
export { vegaProposalState } from './models/vegaProposalState';
export type { vegaProposalTerms } from './models/vegaProposalTerms';
export type { vegaRank } from './models/vegaRank';
export type { vegaRankingScore } from './models/vegaRankingScore';
export type { vegaRecurringTransfer } from './models/vegaRecurringTransfer';
export type { vegaReferralProgram } from './models/vegaReferralProgram';
export type { vegaReferralProgramChanges } from './models/vegaReferralProgramChanges';
export type { vegaReward } from './models/vegaReward';
export type { vegaRewardScore } from './models/vegaRewardScore';
export type { vegaRewardSummary } from './models/vegaRewardSummary';
export type { vegaRiskFactor } from './models/vegaRiskFactor';
export type { vegaScalingFactors } from './models/vegaScalingFactors';
export { vegaSide } from './models/vegaSide';
export type { vegaSimpleModelParams } from './models/vegaSimpleModelParams';
export type { vegaSimpleRiskModel } from './models/vegaSimpleRiskModel';
export type { vegaSpecBindingForCompositePrice } from './models/vegaSpecBindingForCompositePrice';
export type { vegaSpot } from './models/vegaSpot';
export type { vegaSpotProduct } from './models/vegaSpotProduct';
export type { vegaStakingTier } from './models/vegaStakingTier';
export type { vegaStopOrder } from './models/vegaStopOrder';
export { vegaStopOrderStatus } from './models/vegaStopOrderStatus';
export type { vegaSuccessorConfiguration } from './models/vegaSuccessorConfiguration';
export type { vegaTargetStakeParameters } from './models/vegaTargetStakeParameters';
export type { vegaTradableInstrument } from './models/vegaTradableInstrument';
export type { vegaTrade } from './models/vegaTrade';
export { vegaTradeType } from './models/vegaTradeType';
export { vegaTransferType } from './models/vegaTransferType';
export type { vegaUpdateAsset } from './models/vegaUpdateAsset';
export type { vegaUpdateFutureProduct } from './models/vegaUpdateFutureProduct';
export type { vegaUpdateInstrumentConfiguration } from './models/vegaUpdateInstrumentConfiguration';
export type { vegaUpdateMarket } from './models/vegaUpdateMarket';
export type { vegaUpdateMarketConfiguration } from './models/vegaUpdateMarketConfiguration';
export type { vegaUpdateMarketState } from './models/vegaUpdateMarketState';
export type { vegaUpdateMarketStateConfiguration } from './models/vegaUpdateMarketStateConfiguration';
export type { vegaUpdateNetworkParameter } from './models/vegaUpdateNetworkParameter';
export type { vegaUpdatePerpetualProduct } from './models/vegaUpdatePerpetualProduct';
export type { vegaUpdateReferralProgram } from './models/vegaUpdateReferralProgram';
export type { vegaUpdateSpotInstrumentConfiguration } from './models/vegaUpdateSpotInstrumentConfiguration';
export type { vegaUpdateSpotMarket } from './models/vegaUpdateSpotMarket';
export type { vegaUpdateSpotMarketConfiguration } from './models/vegaUpdateSpotMarketConfiguration';
export type { vegaUpdateVolumeDiscountProgram } from './models/vegaUpdateVolumeDiscountProgram';
export { vegaValidatorNodeStatus } from './models/vegaValidatorNodeStatus';
export type { vegaVolumeBenefitTier } from './models/vegaVolumeBenefitTier';
export type { vegaVolumeDiscountProgram } from './models/vegaVolumeDiscountProgram';
export type { vegaVolumeDiscountProgramChanges } from './models/vegaVolumeDiscountProgramChanges';
export type { vegaVote } from './models/vegaVote';
export type { vegaVoteELSPair } from './models/vegaVoteELSPair';
export { vegaVoteValue } from './models/vegaVoteValue';
export type { vegaWithdrawal } from './models/vegaWithdrawal';
export { vegaWithdrawalStatus } from './models/vegaWithdrawalStatus';
export type { vegaWithdrawExt } from './models/vegaWithdrawExt';

export { AccountsService } from './services/AccountsService';
export { AssetsService } from './services/AssetsService';
export { CandlesService } from './services/CandlesService';
export { DataSourcesService } from './services/DataSourcesService';
export { Erc20BridgeService } from './services/Erc20BridgeService';
export { EventsService } from './services/EventsService';
export { FeesService } from './services/FeesService';
export { GamesService } from './services/GamesService';
export { GovernanceService } from './services/GovernanceService';
export { LedgerEntriesService } from './services/LedgerEntriesService';
export { LedgerMovementsService } from './services/LedgerMovementsService';
export { LiquidityService } from './services/LiquidityService';
export { MarginService } from './services/MarginService';
export { MarketsService } from './services/MarketsService';
export { NetworkService } from './services/NetworkService';
export { NetworkHistoryService } from './services/NetworkHistoryService';
export { NodeInformationService } from './services/NodeInformationService';
export { OrdersService } from './services/OrdersService';
export { PartiesService } from './services/PartiesService';
export { PositionsService } from './services/PositionsService';
export { ReferralProgramService } from './services/ReferralProgramService';
export { RewardsService } from './services/RewardsService';
export { TeamsService } from './services/TeamsService';
export { TradesService } from './services/TradesService';
export { TransactionResultsService } from './services/TransactionResultsService';
export { TransfersService } from './services/TransfersService';
export { VolumeDiscountProgramService } from './services/VolumeDiscountProgramService';
