/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum vegaDispatchMetric {
    DISPATCH_METRIC_UNSPECIFIED = 'DISPATCH_METRIC_UNSPECIFIED',
    DISPATCH_METRIC_MAKER_FEES_PAID = 'DISPATCH_METRIC_MAKER_FEES_PAID',
    DISPATCH_METRIC_MAKER_FEES_RECEIVED = 'DISPATCH_METRIC_MAKER_FEES_RECEIVED',
    DISPATCH_METRIC_LP_FEES_RECEIVED = 'DISPATCH_METRIC_LP_FEES_RECEIVED',
    DISPATCH_METRIC_MARKET_VALUE = 'DISPATCH_METRIC_MARKET_VALUE',
    DISPATCH_METRIC_AVERAGE_POSITION = 'DISPATCH_METRIC_AVERAGE_POSITION',
    DISPATCH_METRIC_RELATIVE_RETURN = 'DISPATCH_METRIC_RELATIVE_RETURN',
    DISPATCH_METRIC_RETURN_VOLATILITY = 'DISPATCH_METRIC_RETURN_VOLATILITY',
    DISPATCH_METRIC_VALIDATOR_RANKING = 'DISPATCH_METRIC_VALIDATOR_RANKING',
}
