/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { v1MakerFeesGenerated } from './v1MakerFeesGenerated';
import type { v1PartyAmount } from './v1PartyAmount';
import type { v1ReferrerRewardsGenerated } from './v1ReferrerRewardsGenerated';

export type v1FeesStats = {
    /**
     * Settlement asset of the market.
     */
    asset?: string;
    /**
     * Epoch for which these stats where valid.
     */
    epochSeq?: string;
    /**
     * Maker fees paid by all trade aggressors, and which makers the fees were paid to.
     */
    makerFeesGenerated?: Array<v1MakerFeesGenerated>;
    market?: string;
    /**
     * Total referral discounts applied to all referee taker fees.
     */
    refereesDiscountApplied?: Array<v1PartyAmount>;
    /**
     * Referral rewards generated by all referee taker fees.
     */
    referrerRewardsGenerated?: Array<v1ReferrerRewardsGenerated>;
    /**
     * Total trading fees received and paid by the party.
     */
    totalFeesPaidAndReceived?: Array<v1PartyAmount>;
    /**
     * Total maker fees received by the maker side.
     */
    totalMakerFeesReceived?: Array<v1PartyAmount>;
    /**
     * Total referral rewards received by the referrer of the referral set.
     */
    totalRewardsReceived?: Array<v1PartyAmount>;
    /**
     * Total volume discounts applied to all referee taker fees.
     */
    volumeDiscountApplied?: Array<v1PartyAmount>;
};

